### ISSUE TITLE
Remove player/vehicle map marker

### ISSUE THREAD

**Issue by Whitsel** [7Cav/Tac2-Invade-And-Annex#25]
We have cTab for this

**Comment by RaduM84** [comment]
Isn't it unwise to design mission settings based on features present in optional addons?

**Comment by Whitsel** [comment]
We've been trying to get away from having the map markers for some time and they kinda defeat the purpose of cTab entirely

**Comment by RaduM84** [comment]
Understood

**Comment by RaduM84** [comment]
To clarify : Issue implies turning off the ACE BFT correct?
