### ISSUE TITLE
Steam IDs need to be provided for Mission Controller / Military Police slots

### ISSUE THREAD

**Issue by RaduM84** [7Cav/Tac2-Invade-And-Annex#29]
Steam IDs need to be provided for Mission Controller / Military Police slots

**Comment by RaduM84** [comment]
Aligned variable names

**Comment by RaduM84** [comment]
still not fixed apparently

**Comment by RaduM84** [comment]
Tac2 seems to be cursed. 

System works on Tac1 (future linux machine) and Development 2 (Windows development machine).

Out of ideas.

**Comment by SyniRon** [comment]
worth noting it also doesn't grant zeus with admin consistently
